# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:15
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('meeting_notes', models.TextField(blank=True)),
                ('image_path', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='memo',
            name='meeting_with',
            field=models.ManyToManyField(to='src.Users'),
        ),
    ]
