# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
